# SPDX-FileCopyrightText: 2025 xfnw
#
# SPDX-License-Identifier: CC0-1.0

[criteria.blobs-ok]
description = "may have blobs, but it is obvious where they come from or are reproducible"

[criteria.by-xfnw]
description = "i wrote it, so it must be Secure™®©!"
implies = ["blobs-ok", "skimmed"]

[criteria.no-sus-blobs]
description = "the crate does not include weird blobs"
implies = "blobs-ok"

[criteria.skimmed]
description = "i glanced at it and nothing seemed too suspicious"

[criteria.too-big-to-fail]
description = "popular enough that i dont think it needs to be audited (famous last words)"

[[audits.foxerror]]
version = "0.1.0"
criteria = "by-xfnw"

[[audits.foxerror]]
version = "0.1.1"
criteria = "by-xfnw"

[[audits.foxerror]]
version = "0.1.2"
criteria = "by-xfnw"

[[audits.irc-connect]]
version = "0.1.0"
criteria = "by-xfnw"

[[audits.irc-connect]]
version = "0.1.1"
criteria = "by-xfnw"

[[audits.irc-connect]]
version = "0.2.0"
criteria = "by-xfnw"

[[audits.libloading]]
version = "0.8.8"
criteria = "skimmed"

[[audits.libloading]]
delta = "0.8.8 -> 0.8.9"
criteria = "skimmed"

[[audits.libloading]]
delta = "0.8.8 -> 0.8.9"
criteria = "no-sus-blobs"
notes = "does have weird dlls in tests, but they were not modified in this update"

[[audits.aws-lc-fips-sys]]
version = "0.13.8"
criteria = "too-big-to-fail"

[[audits.aws-lc-fips-sys]]
version = "0.13.9"
criteria = "too-big-to-fail"

[[audits.aws-lc-rs]]
version = "1.14.1"
criteria = "too-big-to-fail"

[[audits.aws-lc-sys]]
version = "0.32.1"
criteria = "too-big-to-fail"

[[audits.aws-lc-sys]]
version = "0.32.2"
criteria = "too-big-to-fail"

[[audits.aws-lc-sys]]
version = "0.32.3"
criteria = "too-big-to-fail"

[[audits.tokio-rustls]]
version = "0.26.3"
criteria = "blobs-ok"
notes = "pem files in tests"

[[audits.tokio-rustls]]
delta = "0.26.3 -> 0.26.4"
criteria = "no-sus-blobs"
notes = "pem files in tests not touched"

[[audits.tokio-rustls]]
delta = "0.26.3 -> 0.26.4"
criteria = "skimmed"

[[audits.cc]]
delta = "1.2.38 -> 1.2.39"
criteria = "blobs-ok"
notes = "has some trivial generated code"

[[audits.cc]]
delta = "1.2.38 -> 1.2.39"
criteria = "skimmed"

[[audits.cc]]
delta = "1.2.39 -> 1.2.40"
criteria = "no-sus-blobs"

[[audits.cc]]
delta = "1.2.39 -> 1.2.40"
criteria = "skimmed"

[[audits.cc]]
delta = "1.2.40 -> 1.2.41"
criteria = "blobs-ok"
notes = "trivial generated code for list of llvm targets had 1 entry added"

[[audits.cc]]
delta = "1.2.40 -> 1.2.41"
criteria = "skimmed"

[[audits.regex-automata]]
delta = "0.4.10 -> 0.4.11"
criteria = "blobs-ok"
notes = "serialized data in tests, has command to generate them in documentation"

[[audits.regex-automata]]
delta = "0.4.10 -> 0.4.11"
criteria = "skimmed"

[[audits.regex-automata]]
delta = "0.4.11 -> 0.4.13"
criteria = "no-sus-blobs"

[[audits.regex-automata]]
delta = "0.4.11 -> 0.4.13"
criteria = "skimmed"

[[audits.regex]]
delta = "1.11.2 -> 1.11.3"
criteria = "skimmed"

[[audits.regex]]
version = "1.11.3"
criteria = "no-sus-blobs"
notes = 'fuzz data got excluded from the crate \o/'

[[audits.regex]]
delta = "1.11.3 -> 1.12.2"
criteria = "no-sus-blobs"

[[audits.regex]]
delta = "1.11.3 -> 1.12.2"
criteria = "skimmed"

[[audits.addr2line]]
delta = "0.24.2 -> 0.25.1"
criteria = "skimmed"

[[audits.addr2line]]
version = "0.25.1"
criteria = "no-sus-blobs"

[[audits.windows-link]]
version = "0.2.0"
criteria = "no-sus-blobs"

[[audits.windows-link]]
version = "0.2.0"
criteria = "skimmed"

[[audits.windows-link]]
delta = "0.2.0 -> 0.2.1"
criteria = "no-sus-blobs"

[[audits.windows-link]]
delta = "0.2.0 -> 0.2.1"
criteria = "skimmed"

[[audits.object]]
delta = "0.36.7 -> 0.37.3"
criteria = "no-sus-blobs"

[[audits.object]]
delta = "0.36.7 -> 0.37.3"
criteria = "skimmed"

[[audits.memchr]]
delta = "2.7.5 -> 2.7.6"
criteria = "no-sus-blobs"

[[audits.memchr]]
delta = "2.7.5 -> 2.7.6"
criteria = "skimmed"

[[audits.backtrace]]
delta = "0.3.75 -> 0.3.76"
criteria = "no-sus-blobs"

[[audits.backtrace]]
delta = "0.3.75 -> 0.3.76"
criteria = "skimmed"

[[audits.gimli]]
delta = "0.31.1 -> 0.32.3"
criteria = "no-sus-blobs"

[[audits.gimli]]
delta = "0.31.1 -> 0.32.3"
criteria = "skimmed"

[[audits.quote]]
delta = "1.0.40 -> 1.0.41"
criteria = "no-sus-blobs"

[[audits.quote]]
delta = "1.0.40 -> 1.0.41"
criteria = "skimmed"

[[audits.zeroize]]
delta = "1.8.1 -> 1.8.2"
criteria = "no-sus-blobs"

[[audits.zeroize]]
delta = "1.8.1 -> 1.8.2"
criteria = "skimmed"

[[audits.serde_core]]
delta = "1.0.226 -> 1.0.228"
criteria = "no-sus-blobs"

[[audits.serde_core]]
delta = "1.0.226 -> 1.0.228"
criteria = "skimmed"

[[audits.serde_core]]
version = "1.0.228"
criteria = "no-sus-blobs"

[[audits.serde_core]]
version = "1.0.228"
criteria = "skimmed"

[[audits.itoa]]
version = "1.0.15"
criteria = "no-sus-blobs"

[[audits.itoa]]
version = "1.0.15"
criteria = "skimmed"

[[audits.ryu]]
version = "1.0.20"
criteria = "blobs-ok"
notes = "has long lists of probably harmless magic numbers"

[[audits.ryu]]
version = "1.0.20"
criteria = "skimmed"

[[audits.rustls-webpki]]
delta = "0.103.6 -> 0.103.7"
criteria = "no-sus-blobs"

[[audits.rustls-webpki]]
delta = "0.103.6 -> 0.103.7"
criteria = "skimmed"

[[audits.rustls-webpki]]
delta = "0.103.7 -> 0.103.8"
criteria = "no-sus-blobs"

[[audits.rustls-webpki]]
delta = "0.103.7 -> 0.103.8"
criteria = "skimmed"

[[audits.find-msvc-tools]]
version = "0.1.3"
criteria = "blobs-ok"
notes = "includes some autogenerated bindings"

[[audits.find-msvc-tools]]
version = "0.1.3"
criteria = "skimmed"

[[audits.find-msvc-tools]]
delta = "0.1.3 -> 0.1.4"
criteria = "no-sus-blobs"

[[audits.find-msvc-tools]]
delta = "0.1.3 -> 0.1.4"
criteria = "skimmed"

[[audits.typenum]]
delta = "1.18.0 -> 1.19.0"
criteria = "blobs-ok"
notes = "some generated files with rather silly formatting"

[[audits.typenum]]
delta = "1.18.0 -> 1.19.0"
criteria = "skimmed"

[[audits.serde_derive]]
delta = "1.0.226 -> 1.0.228"
criteria = "no-sus-blobs"

[[audits.serde_derive]]
delta = "1.0.226 -> 1.0.228"
criteria = "skimmed"

[[audits.serde]]
version = "1.0.228"
criteria = "no-sus-blobs"

[[audits.serde]]
version = "1.0.228"
criteria = "skimmed"

[[audits.anstyle]]
delta = "1.0.11 -> 1.0.13"
criteria = "no-sus-blobs"

[[audits.anstyle]]
delta = "1.0.11 -> 1.0.13"
criteria = "skimmed"

[[audits.libc]]
delta = "0.2.175 -> 0.2.176"
criteria = "no-sus-blobs"

[[audits.libc]]
delta = "0.2.175 -> 0.2.176"
criteria = "skimmed"

[[audits.libc]]
delta = "0.2.176 -> 0.2.177"
criteria = "no-sus-blobs"

[[audits.libc]]
delta = "0.2.176 -> 0.2.177"
criteria = "skimmed"

[[audits.axum]]
delta = "0.8.4 -> 0.8.5"
criteria = "no-sus-blobs"

[[audits.axum]]
delta = "0.8.4 -> 0.8.5"
criteria = "skimmed"

[[audits.axum]]
delta = "0.8.5 -> 0.8.6"
criteria = "no-sus-blobs"

[[audits.axum]]
delta = "0.8.5 -> 0.8.6"
criteria = "skimmed"

[[audits.half]]
delta = "2.6.0 -> 2.7.0"
criteria = "no-sus-blobs"

[[audits.half]]
delta = "2.6.0 -> 2.7.0"
criteria = "skimmed"

[[audits.half]]
delta = "2.7.0 -> 2.7.1"
criteria = "no-sus-blobs"

[[audits.half]]
delta = "2.7.0 -> 2.7.1"
criteria = "skimmed"

[[audits.stable_deref_trait]]
version = "1.2.0"
criteria = "no-sus-blobs"

[[audits.stable_deref_trait]]
version = "1.2.1"
criteria = "no-sus-blobs"

[[audits.stable_deref_trait]]
version = "1.2.0"
criteria = "skimmed"

[[audits.stable_deref_trait]]
version = "1.2.1"
criteria = "skimmed"

[[audits.serde_spanned]]
version = "1.0.3"
criteria = "no-sus-blobs"

[[audits.serde_spanned]]
version = "1.0.3"
criteria = "skimmed"

[[audits.toml_edit]]
delta = "0.23.6 -> 0.23.7"
criteria = "no-sus-blobs"

[[audits.toml_edit]]
delta = "0.23.6 -> 0.23.7"
criteria = "skimmed"

[[audits.tokio-macros]]
delta = "2.5.0 -> 2.6.0"
criteria = "no-sus-blobs"

[[audits.tokio-macros]]
delta = "2.5.0 -> 2.6.0"
criteria = "skimmed"

[[audits.windows-sys]]
version = "0.60.2"
criteria = "too-big-to-fail"
notes = "pile of generated code, but its windows stuff published by microsoft so *shrug*"

[[audits.windows-sys]]
version = "0.61.2"
criteria = "too-big-to-fail"
notes = "pile of generated code, but its windows stuff published by microsoft so *shrug*"

[[audits.windows-targets]]
delta = "0.52.6 -> 0.53.5"
criteria = "no-sus-blobs"

[[audits.windows-targets]]
delta = "0.52.6 -> 0.53.5"
criteria = "skimmed"

[[audits.windows_x86_64_msvc]]
version = "0.53.1"
criteria = "too-big-to-fail"
notes = "contains a precompiled lib file, but its windows stuff published by microsoft so *shrug*"

[[audits.windows_x86_64_gnullvm]]
version = "0.53.1"
criteria = "too-big-to-fail"
notes = "contains a precompiled lib file, but its windows stuff published by microsoft so *shrug*"

[[audits.windows_x86_64_gnu]]
version = "0.53.1"
criteria = "too-big-to-fail"
notes = "contains a precompiled lib file, but its windows stuff published by microsoft so *shrug*"

[[audits.windows_i686_msvc]]
version = "0.53.1"
criteria = "too-big-to-fail"
notes = "contains a precompiled lib file, but its windows stuff published by microsoft so *shrug*"

[[audits.windows_i686_gnu]]
version = "0.53.1"
criteria = "too-big-to-fail"
notes = "contains a precompiled lib file, but its windows stuff published by microsoft so *shrug*"

[[audits.windows_i686_gnullvm]]
version = "0.53.1"
criteria = "too-big-to-fail"
notes = "contains a precompiled lib file, but its windows stuff published by microsoft so *shrug*"

[[audits.windows_aarch64_msvc]]
version = "0.53.1"
criteria = "too-big-to-fail"
notes = "contains a precompiled lib file, but its windows stuff published by microsoft so *shrug*"

[[audits.windows_aarch64_gnullvm]]
version = "0.53.1"
criteria = "too-big-to-fail"
notes = "contains a precompiled lib file, but its windows stuff published by microsoft so *shrug*"

[[audits.toml_datetime]]
delta = "0.7.2 -> 0.7.3"
criteria = "no-sus-blobs"

[[audits.toml_datetime]]
delta = "0.7.2 -> 0.7.3"
criteria = "skimmed"

[[audits.socket2]]
delta = "0.6.0 -> 0.6.1"
criteria = "no-sus-blobs"

[[audits.socket2]]
delta = "0.6.0 -> 0.6.1"
criteria = "skimmed"

[[audits.getrandom]]
delta = "0.3.3 -> 0.3.4"
criteria = "no-sus-blobs"

[[audits.getrandom]]
delta = "0.3.3 -> 0.3.4"
criteria = "skimmed"

[[audits.generic-array]]
delta = "0.14.7 -> 0.14.9"
criteria = "no-sus-blobs"

[[audits.generic-array]]
delta = "0.14.7 -> 0.14.9"
criteria = "skimmed"

[[audits.regex-syntax]]
delta = "0.8.6 -> 0.8.8"
criteria = "no-sus-blobs"

[[audits.regex-syntax]]
delta = "0.8.6 -> 0.8.8"
criteria = "skimmed"

[[audits.cfg-if]]
delta = "1.0.3 -> 1.0.4"
criteria = "no-sus-blobs"

[[audits.cfg-if]]
delta = "1.0.3 -> 1.0.4"
criteria = "skimmed"

[[audits.toml_parser]]
delta = "1.0.3 -> 1.0.4"
criteria = "no-sus-blobs"

[[audits.toml_parser]]
delta = "1.0.3 -> 1.0.4"
criteria = "skimmed"

[[audits.toml_writer]]
delta = "1.0.3 -> 1.0.4"
criteria = "no-sus-blobs"

[[audits.toml_writer]]
delta = "1.0.3 -> 1.0.4"
criteria = "skimmed"

[[audits.tokio]]
delta = "1.47.1 -> 1.48.0"
criteria = "no-sus-blobs"

[[audits.tokio]]
delta = "1.47.1 -> 1.48.0"
criteria = "skimmed"

[[audits.rustls]]
delta = "0.23.32 -> 0.23.33"
criteria = "no-sus-blobs"

[[audits.rustls]]
delta = "0.23.32 -> 0.23.33"
criteria = "skimmed"

[[audits.rustls]]
delta = "0.23.33 -> 0.23.35"
criteria = "no-sus-blobs"

[[audits.rustls]]
delta = "0.23.33 -> 0.23.35"
criteria = "skimmed"

[[audits.mark-tree]]
version = "0.1.0"
criteria = "by-xfnw"

[[audits.bitflags]]
delta = "2.9.4 -> 2.10.0"
criteria = "no-sus-blobs"

[[audits.bitflags]]
delta = "2.9.4 -> 2.10.0"
criteria = "skimmed"

[[audits.mio]]
delta = "1.0.4 -> 1.1.0"
criteria = "no-sus-blobs"

[[audits.mio]]
delta = "1.0.4 -> 1.1.0"
criteria = "skimmed"

[[audits.utf8-width]]
version = "0.1.7"
criteria = "no-sus-blobs"

[[audits.utf8-width]]
version = "0.1.7"
criteria = "skimmed"

[[audits.html-escape]]
version = "0.2.13"
criteria = "blobs-ok"
notes = "has a table of html entity names"

[[audits.html-escape]]
version = "0.2.13"
criteria = "skimmed"

[[audits.signal-hook-registry]]
version = "1.4.6"
criteria = "no-sus-blobs"

[[audits.signal-hook-registry]]
version = "1.4.6"
criteria = "skimmed"

[[audits.rustls-pki-types]]
delta = "1.12.0 -> 1.13.0"
criteria = "skimmed"

[[audits.lazy-regex]]
delta = "3.4.1 -> 3.4.2"
criteria = "no-sus-blobs"

[[audits.lazy-regex]]
delta = "3.4.1 -> 3.4.2"
criteria = "skimmed"

[[audits.lazy-regex-proc_macros]]
delta = "3.4.1 -> 3.4.2"
criteria = "no-sus-blobs"

[[audits.lazy-regex-proc_macros]]
delta = "3.4.1 -> 3.4.2"
criteria = "skimmed"

[[audits.aho-corasick]]
delta = "1.1.3 -> 1.1.4"
criteria = "no-sus-blobs"

[[audits.aho-corasick]]
delta = "1.1.3 -> 1.1.4"
criteria = "skimmed"

[[audits.crypto-common]]
delta = "0.1.6 -> 0.1.7"
criteria = "no-sus-blobs"

[[audits.crypto-common]]
delta = "0.1.6 -> 0.1.7"
criteria = "skimmed"
